package dev.dreamcraft.protection.command;

import dev.dreamcraft.protection.domain.model.City;
import dev.dreamcraft.protection.domain.model.OwnerType;
import dev.dreamcraft.protection.domain.model.Ward;
import dev.dreamcraft.protection.domain.model.WardPermission;
import dev.dreamcraft.protection.domain.service.CityService;
import dev.dreamcraft.protection.domain.service.WardService;
import dev.dreamcraft.protection.integration.worldguard.WorldGuardAdapter;
import net.kyori.adventure.text.format.NamedTextColor;
import org.bukkit.Bukkit;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.command.TabCompleter;
import org.bukkit.entity.Player;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.UUID;

import static dev.dreamcraft.protection.command.CommandMessages.*;

/**
 * Handles all /ward (alias: /w) subcommands.
 *
 * <p>Delegates all business logic to {@link WardService} and opens menus through
 * the shared {@link WardMenuFacade} — the exact same menu as /protection claim.
 */
public final class WardCommand implements CommandExecutor, TabCompleter {

    private static final String USE_PERM = "dreamcraft.ward.use";
    private static final String ADMIN_PERM = "dreamcraft.ward.admin";
    /** VIP/menu permission: admins (ward.admin) or holders of this node may open /ward menu. */
    private static final String MENU_PERM = "dreamcraft.ward.menu";

    private final WardService wardService;
    private final CityService cityService;
    private final WorldGuardAdapter worldGuardAdapter;
    private final dev.dreamcraft.protection.ui.WardItems wardItems;
    /** Shared menu façade — same menu as /protection claim. */
    private final WardMenuFacade menuFacade;
    /** Optional: item-based upkeep deposits. */
    private final dev.dreamcraft.protection.service.WardUpkeepService upkeepService;

    public WardCommand(WardService wardService,
                       CityService cityService,
                       WorldGuardAdapter worldGuardAdapter,
                       dev.dreamcraft.protection.ui.WardItems wardItems,
                       WardMenuFacade menuFacade,
                       dev.dreamcraft.protection.service.WardUpkeepService upkeepService) {
        this.wardService = wardService;
        this.cityService = cityService;
        this.worldGuardAdapter = worldGuardAdapter;
        this.wardItems = wardItems;
        this.menuFacade = menuFacade;
        this.upkeepService = upkeepService;
    }

    @Override
    public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
        if (!(sender instanceof Player player)) {
            sender.sendMessage("§cEste comando solo puede ser usado por jugadores.");
            return true;
        }
        if (!player.hasPermission(USE_PERM)) {
            error(player, WARD_PREFIX, "No tienes permiso para usar este comando.");
            return true;
        }
        if (args.length == 0) {
            sendHelp(player);
            return true;
        }
        try {
            return switch (args[0].toLowerCase(Locale.ROOT)) {
                case "create" -> handleCreate(player);
                case "rename" -> handleRename(player, args);
                case "info" -> handleInfo(player, args);
                case "delete" -> handleDelete(player, args);
                case "score" -> handleScore(player, args);
                case "upkeep" -> handleUpkeep(player, args);
                case "transfer" -> handleTransfer(player, args);
                case "permissions" -> handlePermissions(player, args);
                case "city" -> handleCity(player, args);
                case "menu" -> handleMenu(player, args);
                case "give" -> handleGive(player);
                default -> {
                    error(player, WARD_PREFIX, "Subcomando desconocido: " + args[0]);
                    sendHelp(player);
                    yield true;
                }
            };
        } catch (RuntimeException e) {
            if (!handleDomainException(player, WARD_PREFIX, e)) {
                error(player, WARD_PREFIX, "Error: " + e.getMessage());
            }
            return true;
        }
    }

    // ── Subcommand handlers ────────────────────────────────────────────────────

    private boolean handleCreate(Player player) {
        Ward ward = wardService.createWard(
                player.getUniqueId(),
                OwnerType.PLAYER,
                null,
                player.getWorld().getName(),
                player.getLocation().getBlockX(),
                player.getLocation().getBlockY(),
                player.getLocation().getBlockZ(),
                null // unique friendly name generated by the domain service
        );
        // Create the WorldGuard region and link it back
        String regionId = worldGuardAdapter.createRegion(ward, player.getWorld().getName(), -64, 320);
        if (regionId != null) {
            wardService.assignWorldGuardRegion(ward, regionId);
        }
        ok(player, WARD_PREFIX, "Ward §f" + ward.name() + "§a creado (tier " + ward.tier() + ", radio " + ward.radius() + ").");
        title(player, "Ward Creado", ward.name(), NamedTextColor.AQUA);
        return true;
    }

    /** /ward give — admin only: hands the special ward block item to the caller. */
    private boolean handleGive(Player player) {
        if (!player.hasPermission(ADMIN_PERM)) {
            error(player, WARD_PREFIX, "No tienes permiso para este comando.");
            return true;
        }
        player.getInventory().addItem(wardItems.createWardItem());
        ok(player, WARD_PREFIX, "Baliza de Ward entregada. Colocala para fundar un Ward.");
        return true;
    }

    /**
     * /ward rename <nombre...> — renames the resolved Ward (owner or admin only).
     * Accepts multi-word names; uniqueness is enforced by the domain service.
     */
    private boolean handleRename(Player player, String[] args) {
        if (args.length < 2) {
            error(player, WARD_PREFIX, "Uso: /ward rename <nombre>");
            return true;
        }
        Ward ward = resolveWard(player, args);
        if (ward == null) return true;
        if (!ward.ownerId().equals(player.getUniqueId()) && !player.hasPermission(ADMIN_PERM)) {
            error(player, WARD_PREFIX, "Solo el owner puede renombrar el Ward.");
            return true;
        }
        String newName = String.join(" ", java.util.Arrays.copyOfRange(args, 1, args.length)).trim();
        String oldName = ward.name();
        try {
            wardService.renameWard(ward, newName);
        } catch (IllegalArgumentException e) {
            error(player, WARD_PREFIX, e.getMessage());
            return true;
        }
        ok(player, WARD_PREFIX, "Ward §f" + oldName + "§a renombrado a §f" + ward.name() + "§a.");
        title(player, "Ward Renombrado", ward.name(), NamedTextColor.AQUA);
        return true;
    }

    private boolean handleInfo(Player player, String[] args) {
        Ward ward = resolveWard(player, args);
        if (ward == null) return true;
        info(player, WARD_PREFIX, "Nombre: §f" + ward.name());
        info(player, WARD_PREFIX, "ID: " + ward.id());
        info(player, WARD_PREFIX, "Owner: " + CommandMessages.resolveName(ward.ownerId()));
        info(player, WARD_PREFIX, "Tier: " + ward.tier() + " | Score: " + ward.baseScore());
        info(player, WARD_PREFIX, "Radio: " + ward.radius() + " | Upkeep: " + ward.upkeepBalance());
        info(player, WARD_PREFIX, "Centro: " + ward.centerX() + ", " + ward.centerY() + ", " + ward.centerZ());
        if (ward.hasCityMembership()) {
            cityService.findById(ward.cityId()).ifPresent(c ->
                    info(player, WARD_PREFIX, "Ciudad: " + c.name()));
        }
        return true;
    }

    private boolean handleDelete(Player player, String[] args) {
        Ward ward = resolveWard(player, args);
        if (ward == null) return true;
        if (!ward.ownerId().equals(player.getUniqueId()) && !player.hasPermission(ADMIN_PERM)) {
            error(player, WARD_PREFIX, "Solo el owner puede eliminar el Ward.");
            return true;
        }
        worldGuardAdapter.removeRegion(ward);
        wardService.delete(ward);
        ok(player, WARD_PREFIX, "Ward eliminado.");
        return true;
    }

    private boolean handleScore(Player player, String[] args) {
        Ward ward = resolveWard(player, args);
        if (ward == null) return true;
        if (args.length >= 3 && "add".equalsIgnoreCase(args[1])) {
            if (!ward.ownerId().equals(player.getUniqueId()) && !player.hasPermission(ADMIN_PERM)) {
                error(player, WARD_PREFIX, "Solo el owner puede modificar el score.");
                return true;
            }
            try {
                int delta = Integer.parseInt(args[2]);
                wardService.addBaseScore(ward, delta);
                worldGuardAdapter.resizeRegion(ward, -64, 320);
                ok(player, WARD_PREFIX, "Score actualizado: " + ward.baseScore() + " (tier " + ward.tier() + ").");
            } catch (NumberFormatException e) {
                error(player, WARD_PREFIX, "Cantidad inválida: " + args[2]);
            }
            return true;
        }
        info(player, WARD_PREFIX, "Score: " + ward.baseScore() + " | Tier: " + ward.tier());
        return true;
    }

    /**
     * /ward upkeep                          — shows balance and next charge
     * /ward upkeep deposit <material> <n>   — consumes n items, credits units
     * /ward upkeep credit <n>               — (admin/debug) credits raw units
     */
    private boolean handleUpkeep(Player player, String[] args) {
        Ward ward = resolveWard(player, args);
        if (ward == null) return true;

        if (args.length >= 2 && "deposit".equalsIgnoreCase(args[1])) {
            if (upkeepService == null) {
                error(player, WARD_PREFIX, "Depósitos no disponibles.");
                return true;
            }
            if (args.length < 4) {
                error(player, WARD_PREFIX, "Uso: /ward upkeep deposit <material> <cantidad>");
                info(player, WARD_PREFIX, "Aceptados: " + acceptedMaterialsList());
                return true;
            }
            org.bukkit.Material material = upkeepService.matchAccepted(args[2]).orElse(null);
            if (material == null) {
                error(player, WARD_PREFIX, "Material no aceptado: " + args[2]);
                info(player, WARD_PREFIX, "Aceptados: " + acceptedMaterialsList());
                return true;
            }
            int amount;
            try {
                amount = Integer.parseInt(args[3]);
            } catch (NumberFormatException e) {
                error(player, WARD_PREFIX, "Cantidad inválida: " + args[3]);
                return true;
            }
            if (amount <= 0) {
                error(player, WARD_PREFIX, "La cantidad debe ser mayor a 0.");
                return true;
            }
            int carried = countMaterial(player, material);
            if (carried < amount) {
                error(player, WARD_PREFIX, "Solo tenés " + carried + "x "
                        + upkeepService.displayName(material) + ".");
                return true;
            }
            upkeepService.consumeFromInventory(player, material, amount);
            var receipt = upkeepService.deposit(ward, player, material, amount);
            ok(player, WARD_PREFIX, "Depositaste " + receipt.amount() + "x §f"
                    + upkeepService.displayName(receipt.material()) + "§a → +"
                    + receipt.unitsCredited() + " unidades. Balance: §f" + receipt.newBalance());
            return true;
        }

        if (args.length >= 2 && "credit".equalsIgnoreCase(args[1])) {
            if (!player.hasPermission(ADMIN_PERM)) {
                error(player, WARD_PREFIX, "Solo admins puede acreditar unidades directas.");
                return true;
            }
            try {
                int units = Integer.parseInt(args[2]);
                wardService.depositUpkeep(ward, units);
                ok(player, WARD_PREFIX, "Acreditadas " + units + " unidades. Balance: " + ward.upkeepBalance());
            } catch (NumberFormatException e) {
                error(player, WARD_PREFIX, "Cantidad inválida: " + args[2]);
            }
            return true;
        }

        info(player, WARD_PREFIX, "Upkeep: " + ward.upkeepBalance() + " | Próximo cobro: " + ward.nextUpkeepAt());
        if (upkeepService != null) {
            info(player, WARD_PREFIX, "Depositar ítems: /ward upkeep deposit <material> <n>");
            info(player, WARD_PREFIX, "Aceptados: " + acceptedMaterialsList());
        }
        return true;
    }

    private String acceptedMaterialsList() {
        StringBuilder sb = new StringBuilder();
        upkeepService.acceptedMaterials().forEach((mat, units) -> {
            if (sb.length() > 0) sb.append("§7, ");
            sb.append("§f").append(upkeepService.displayName(mat)).append(" §7(×").append(units).append(")");
        });
        return sb.toString();
    }

    private int countMaterial(Player player, org.bukkit.Material material) {
        int total = 0;
        for (org.bukkit.inventory.ItemStack item : player.getInventory().getStorageContents()) {
            if (item != null && item.getType() == material) total += item.getAmount();
        }
        return total;
    }

    private boolean handleTransfer(Player player, String[] args) {
        if (args.length < 2) {
            error(player, WARD_PREFIX, "Uso: /ward transfer <jugador>");
            return true;
        }
        Ward ward = resolveWard(player, args);
        if (ward == null) return true;
        if (!ward.ownerId().equals(player.getUniqueId())) {
            error(player, WARD_PREFIX, "Solo el owner puede transferir el Ward.");
            return true;
        }
        Player target = Bukkit.getPlayerExact(args[1]);
        if (target == null) {
            error(player, WARD_PREFIX, "Jugador " + args[1] + " no encontrado o no está en línea.");
            return true;
        }
        wardService.transferOwnership(ward, target.getUniqueId(), OwnerType.PLAYER);
        worldGuardAdapter.syncOwner(ward);
        ok(player, WARD_PREFIX, "Ward transferido a " + target.getName() + ".");
        return true;
    }

    private boolean handlePermissions(Player player, String[] args) {
        Ward ward = resolveWard(player, args);
        if (ward == null) return true;
        if (args.length >= 3) {
            if (!ward.ownerId().equals(player.getUniqueId())) {
                error(player, WARD_PREFIX, "Solo el owner puede cambiar permisos.");
                return true;
            }
            WardPermission perm;
            try {
                perm = WardPermission.valueOf(args[1].toUpperCase(Locale.ROOT));
            } catch (IllegalArgumentException e) {
                error(player, WARD_PREFIX, "Permiso inválido: " + args[1]);
                return true;
            }
            if ("grant".equalsIgnoreCase(args[2])) {
                ward.grantPermission(perm);
                wardService.assignWorldGuardRegion(ward, ward.worldGuardRegionId());
                ok(player, WARD_PREFIX, "Permiso " + perm.name() + " concedido.");
            } else if ("revoke".equalsIgnoreCase(args[2])) {
                ward.revokePermission(perm);
                wardService.assignWorldGuardRegion(ward, ward.worldGuardRegionId());
                ok(player, WARD_PREFIX, "Permiso " + perm.name() + " revocado.");
            } else {
                error(player, WARD_PREFIX, "Uso: /ward permissions <perm> <grant|revoke>");
            }
            return true;
        }
        info(player, WARD_PREFIX, "Permisos: " + ward.permissions());
        return true;
    }

    private boolean handleCity(Player player, String[] args) {
        Ward ward = resolveWard(player, args);
        if (ward == null) return true;
        if (args.length < 2) {
            if (ward.hasCityMembership()) {
                cityService.findById(ward.cityId()).ifPresent(c ->
                        info(player, WARD_PREFIX, "Ciudad: " + c.name()));
            } else {
                info(player, WARD_PREFIX, "Este Ward no pertenece a ninguna ciudad.");
            }
            return true;
        }
        if ("annex".equalsIgnoreCase(args[1])) {
            if (!ward.ownerId().equals(player.getUniqueId())) {
                error(player, WARD_PREFIX, "Solo el owner puede anexar el Ward.");
                return true;
            }
            var optCity = cityService.findByMember(player.getUniqueId());
            if (optCity.isEmpty()) {
                error(player, WARD_PREFIX, "No eres miembro de ninguna ciudad.");
                return true;
            }
            City city = optCity.get();
            wardService.setCityMembership(ward, city.id());
            syncCityMembership(ward, city);
            ok(player, WARD_PREFIX, "Ward anexado a la ciudad " + city.name() + ".");
            return true;
        }
        if ("leave".equalsIgnoreCase(args[1])) {
            if (!ward.ownerId().equals(player.getUniqueId())) {
                error(player, WARD_PREFIX, "Solo el owner puede desvincular el Ward.");
                return true;
            }
            wardService.setCityMembership(ward, null);
            ok(player, WARD_PREFIX, "Ward desvinculado de la ciudad.");
            return true;
        }
        error(player, WARD_PREFIX, "Uso: /ward city [annex|leave]");
        return true;
    }

    private boolean handleMenu(Player player, String[] args) {
        if (!canOpenWardMenu(player)) {
            error(player, WARD_PREFIX, "El menú del Ward está reservado a admins y VIPs.");
            return true;
        }
        Ward ward = resolveWard(player, args);
        if (ward == null) return true;
        openWardMenu(player, ward);
        return true;
    }

    /**
     * Menu access gate shared with the ward block listener:
     * admins ({@code dreamcraft.ward.admin}) or VIPs ({@code dreamcraft.ward.menu}).
     */
    public boolean canOpenWardMenu(Player player) {
        return player.hasPermission(ADMIN_PERM) || player.hasPermission(MENU_PERM);
    }

    // ── Menu opening ───────────────────────────────────────────────────────────

    public void openWardMenu(Player player, Ward ward) {
        menuFacade.open(player, ward);
    }

    // ── Ward resolution ────────────────────────────────────────────────────────

    /**
     * Resolves the ward from args: tries UUID first, then player's location, then owner's first ward.
     */
    private Ward resolveWard(Player player, String[] args) {
        // If a sub-command is given as args[0], the ward ID may be in args[1] for some commands
        for (int i = 1; i < args.length; i++) {
            try {
                UUID id = UUID.fromString(args[i]);
                return wardService.findById(id).orElse(null);
            } catch (IllegalArgumentException ignored) {}
        }
        // Try location-based lookup
        var atLocation = wardService.findAtLocation(
                player.getWorld().getName(),
                player.getLocation().getBlockX(),
                player.getLocation().getBlockZ());
        if (atLocation.isPresent()) return atLocation.get();
        // Try owner's first ward
        var byOwner = wardService.findByOwner(player.getUniqueId());
        if (!byOwner.isEmpty()) return byOwner.iterator().next();
        error(player, WARD_PREFIX, "No se encontró ningún Ward. Usa /ward create primero.");
        return null;
    }

    private void syncCityMembership(Ward ward, dev.dreamcraft.protection.domain.model.City city) {
        if (!worldGuardAdapter.isAvailable()) return;
        for (UUID memberId : city.members().keySet()) {
            worldGuardAdapter.addMember(ward, memberId);
        }
    }

    // ── Help ──────────────────────────────────────────────────────────────────

    private void sendHelp(Player player) {
        player.sendMessage("§b§lDreamCraft Ward");
        player.sendMessage("§7Gestiona tu territorio Ward.");
        player.sendMessage(" ");
        player.sendMessage("§f/ward create              §7— Crear Ward en tu posición");
        player.sendMessage("§f/ward rename <nombre>    §7— Renombrar tu Ward");
        player.sendMessage("§f/ward give               §7— (Admin) Recibir la Baliza de Ward");
        player.sendMessage("§f/ward info [id]          §7— Ver información del Ward");
        player.sendMessage("§f/ward menu [id]          §7— Abrir menú del Ward §8(admins/VIPs)");
        player.sendMessage("§f/ward score [add <n>]    §7— Ver/añadir score");
        player.sendMessage("§f/ward upkeep [deposit <material> <n>] §7— Ver/depositar upkeep");
        player.sendMessage("§f/ward transfer <jugador> §7— Transferir ownership");
        player.sendMessage("§f/ward permissions [perm grant|revoke] §7— Gestionar permisos");
        player.sendMessage("§f/ward city [annex|leave] §7— Anexar/desvincular de ciudad");
        player.sendMessage("§f/ward delete [id]       §7— Eliminar Ward");
    }

    // ── Tab completion ─────────────────────────────────────────────────────────

    @Override
    public List<String> onTabComplete(CommandSender sender, Command command, String alias, String[] args) {
        List<String> completions = new ArrayList<>();
        if (args.length == 1) {
            List<String> subs = List.of("create", "rename", "info", "delete", "score", "upkeep", "transfer", "permissions", "city", "menu", "give");
            filter(subs, args[0]).forEach(completions::add);
            return completions;
        }
        if (args.length == 2) {
            String sub = args[0].toLowerCase(Locale.ROOT);
            switch (sub) {
                case "transfer" -> filter(onlinePlayers(args[1]), args[1]).forEach(completions::add);
                case "permissions" -> {
                    for (WardPermission p : WardPermission.values()) completions.add(p.name().toLowerCase());
                    filter(completions, args[1]);
                }
                case "score" -> filter(List.of("add"), args[1]).forEach(completions::add);
                case "upkeep" -> {
                    List<String> opts = new ArrayList<>(List.of("deposit"));
                    if (sender.hasPermission(ADMIN_PERM)) opts.add("credit");
                    filter(opts, args[1]).forEach(completions::add);
                }
                case "city" -> filter(List.of("annex", "leave"), args[1]).forEach(completions::add);
                default -> wardIdsOf(sender).stream().filter(id -> id.startsWith(args[1])).forEach(completions::add);
            }
            return completions;
        }
        if (args.length == 3) {
            String sub = args[0].toLowerCase(Locale.ROOT);
            if ("upkeep".equals(sub) && "deposit".equalsIgnoreCase(args[1]) && upkeepService != null) {
                upkeepService.acceptedMaterials().keySet().stream()
                        .map(Enum::name)
                        .map(String::toLowerCase)
                        .filter(m -> m.startsWith(args[2].toLowerCase(Locale.ROOT)))
                        .forEach(completions::add);
                return completions;
            }
            if ("permissions".equals(sub)) {
                filter(List.of("grant", "revoke"), args[2]).forEach(completions::add);
                return completions;
            }
        }
        return List.of();
    }

    private List<String> onlinePlayers(String prefix) {
        List<String> names = new ArrayList<>();
        Bukkit.getOnlinePlayers().stream()
                .map(Player::getName)
                .filter(n -> n.toLowerCase(Locale.ROOT).startsWith(prefix.toLowerCase(Locale.ROOT)))
                .forEach(names::add);
        return names;
    }

    private List<String> wardIdsOf(CommandSender sender) {
        if (!(sender instanceof Player player)) return List.of();
        return wardService.findByOwner(player.getUniqueId()).stream()
                .map(w -> w.id().toString())
                .toList();
    }

    private List<String> filter(List<String> options, String prefix) {
        return options.stream()
                .filter(s -> s.toLowerCase(Locale.ROOT).startsWith(prefix.toLowerCase(Locale.ROOT)))
                .toList();
    }
}
