services:
  config-sync:
    image: alpine
    volumes:
      - ./plugin-configs:/src:ro
      - ./data/plugins:/dest
    command: sh -c "mkdir -p /dest && cp -rf /src/. /dest/"

  mc:
    image: itzg/minecraft-server:stable-java25
    pull_policy: daily
    tty: true
    stdin_open: true
    depends_on:
      config-sync:
        condition: service_completed_successfully
    ports:
      - "25565:25565"
    environment:
      MEMORY: 6G
      EULA: TRUE
      TYPE: PAPER
      VERSION: 26.1.2
      PAPER_BUILD: 74
      ONLINE_MODE: false
      SEED: 6006216005338798975
      PLUGINS: |
        https://cdn.modrinth.com/data/Lu3KuzdV/versions/Kma0kBsY/CoreProtect-CE-24.0.jar
        https://download.luckperms.net/1658/bukkit/loader/LuckPerms-Bukkit-5.5.71.jar
        https://repo.nickuc.com/files/latest/nLogin.jar
        https://cdn.modrinth.com/data/HYKaKraK/versions/h0ncTpUP/packetevents-spigot-2.13.0.jar
        https://github.com/EssentialsX/Essentials/releases/download/2.22.0/EssentialsX-2.22.0.jar
        https://github.com/EssentialsX/Essentials/releases/download/2.22.0/EssentialsXChat-2.22.0.jar
        https://github.com/EssentialsX/Essentials/releases/download/2.22.0/EssentialsXSpawn-2.22.0.jar
        https://cdn.modrinth.com/data/1u6JkXh5/versions/F5ea2ov3/worldedit-bukkit-7.4.5.jar
        https://cdn.modrinth.com/data/DKY9btbd/versions/btHBavWa/worldguard-bukkit-7.0.18.jar
        https://cdn.modrinth.com/data/TsLS8Py5/versions/wXS6bHiC/SkinsRestorer.jar
        https://cdn.modrinth.com/data/P1OZGk5p/versions/ZH8459B6/ViaVersion-5.11.0.jar
        https://cdn.modrinth.com/data/NpvuJQoq/versions/hYhg2QBT/ViaBackwards-5.11.0.jar
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data