package dev.dreamcraft.protection.listener;

import dev.dreamcraft.protection.command.CommandMessages;
import dev.dreamcraft.protection.domain.model.OwnerType;
import dev.dreamcraft.protection.domain.model.Ward;
import dev.dreamcraft.protection.domain.service.WardService;
import dev.dreamcraft.protection.integration.worldguard.WorldGuardAdapter;
import dev.dreamcraft.protection.ui.WardItems;
import net.kyori.adventure.text.format.NamedTextColor;
import org.bukkit.block.Block;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.Listener;
import org.bukkit.event.block.Action;
import org.bukkit.event.block.BlockBreakEvent;
import org.bukkit.event.block.BlockPlaceEvent;
import org.bukkit.event.player.PlayerInteractEvent;
import org.bukkit.inventory.EquipmentSlot;

import java.util.Optional;
import java.util.function.BiConsumer;

/**
 * Listener for the special Ward block.
 *
 * <p>Behaviour contract:
 * <ul>
 *   <li>Placing the Ward item founds a Ward whose protection radius is centered
 *       on the placed block.</li>
 *   <li>Breaking the center block dissolves the Ward (owner or admin only).</li>
 *   <li>Right-clicking the center block opens the Ward menu (admins/VIPs only,
 *       same restriction as {@code /ward menu}).</li>
 * </ul>
 */
public final class WardItemListener implements Listener {

    private final WardItems wardItems;
    private final WardService wardService;
    private final WorldGuardAdapter worldGuardAdapter;
    private final BiConsumer<Player, Ward> menuOpener;
    private final java.util.function.Predicate<Player> menuAccess;
    private final Runnable saveAction;

    public WardItemListener(WardItems wardItems,
                            WardService wardService,
                            WorldGuardAdapter worldGuardAdapter,
                            BiConsumer<Player, Ward> menuOpener,
                            java.util.function.Predicate<Player> menuAccess,
                            Runnable saveAction) {
        this.wardItems = wardItems;
        this.wardService = wardService;
        this.worldGuardAdapter = worldGuardAdapter;
        this.menuOpener = menuOpener;
        this.menuAccess = menuAccess;
        this.saveAction = saveAction;
    }

    // ── Block place ───────────────────────────────────────────────────────────

    @EventHandler(priority = EventPriority.HIGH, ignoreCancelled = true)
    public void onBlockPlace(BlockPlaceEvent event) {
        if (!wardItems.isWardItem(event.getItemInHand())) return;

        Player player = event.getPlayer();
        Block block = event.getBlockPlaced();
        String world = block.getWorld().getName();

        // No founding a Ward inside another Ward's radius
        if (wardService.findAtLocation(world, block.getX(), block.getZ()).isPresent()) {
            event.setCancelled(true);
            player.sendMessage(CommandMessages.prefixed("ward",
                    "Esta área ya pertenece a otro Núcleo.", NamedTextColor.RED));
            return;
        }

        Ward ward = wardService.createWard(
                player.getUniqueId(),
                OwnerType.PLAYER,
                null,
                world,
                block.getX(), block.getY(), block.getZ(),
                null // unique friendly name generated by the domain service
        );
        String regionId = worldGuardAdapter.createRegion(ward, world, -64, 320);
        if (regionId != null) {
            wardService.assignWorldGuardRegion(ward, regionId);
        }
        saveAction.run();
        player.sendMessage(CommandMessages.prefixed("ward",
                "Núcleo §f" + ward.name() + "§a despertado (fase " + ward.tier()
                        + ", radio " + ward.radius() + ").",
                NamedTextColor.GREEN));
    }

    // ── Block break ───────────────────────────────────────────────────────────

    @EventHandler(priority = EventPriority.HIGH, ignoreCancelled = true)
    public void onBlockBreak(BlockBreakEvent event) {
        Block block = event.getBlock();
        Optional<Ward> center = wardService.findByCenter(
                block.getWorld().getName(), block.getX(), block.getY(), block.getZ());
        if (center.isEmpty()) return;

        Player player = event.getPlayer();
        Ward ward = center.get();
        boolean admin = player.hasPermission("dreamcraft.ward.admin");
        if (!ward.ownerId().equals(player.getUniqueId()) && !admin) {
            event.setCancelled(true);
            player.sendMessage("§c[Sincronía] Solo el owner puede retirar su Núcleo de Sincronía.");
            return;
        }
        worldGuardAdapter.removeRegion(ward);
        wardService.delete(ward);
        saveAction.run();
        player.sendMessage(CommandMessages.prefixed("ward",
                "Núcleo §f" + ward.name() + "§a desactivado. Área liberada.",
                NamedTextColor.GREEN));
    }

    // ── Right-click ───────────────────────────────────────────────────────────

    @EventHandler(priority = EventPriority.HIGH, ignoreCancelled = true)
    public void onPlayerInteract(PlayerInteractEvent event) {
        if (event.getAction() != Action.RIGHT_CLICK_BLOCK) return;
        if (event.getHand() != EquipmentSlot.HAND || event.getClickedBlock() == null) return;

        Block block = event.getClickedBlock();
        Optional<Ward> center = wardService.findByCenter(
                block.getWorld().getName(), block.getX(), block.getY(), block.getZ());
        if (center.isEmpty()) return;

        event.setCancelled(true);
        Player player = event.getPlayer();
        if (!menuAccess.test(player)) {
            player.sendMessage(CommandMessages.prefixed("ward",
                    "El menú del Núcleo está reservado a admins y VIPs.", NamedTextColor.RED));
            return;
        }
        menuOpener.accept(player, center.get());
    }
}
